name: Build RedTrace Windows

on:
  workflow_dispatch:
  push:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.ps1"
      - "Assets/**"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Build RedTrace
        shell: pwsh
        run: .\build.ps1

      - uses: actions/upload-artifact@v4
        with:
          name: RedTrace-Windows-x64
          path: publish\*
